FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Create the ml directory structure if it doesn't exist
RUN mkdir -p ml

# Create an empty model file if it doesn't exist
RUN if [ ! -f "ml/model.pkl" ]; then touch ml/model.pkl; fi

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
